name: store_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.26.0
  dotted_border: ^1.0.7
  flutter_swiper: ^1.1.6

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
   - family: "PoppinsRegular"
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf

   - family: "PoppinsBold"
     fonts:
       - asset: assets/fonts/Poppins.ttf

   - family: "Cabin"
     fonts:
       - asset: assets/fonts/cabin.ttf

   - family: "MetroPolisRegular"
     fonts:
       - asset: assets/fonts/Metropolis-Regular.otf